name: Node.js CI

on: [push]

jobs:
  dependencies:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
      - uses: actions/cache@v3
        with:
            key: ${{ runner.os }}-build-dependencies-${{ hashFiles('**/package-lock.json') }}
            path: |
              ./node_modules
      - run: npm install
  build:
    needs: dependencies

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
      - uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-build-dependencies-${{ hashFiles('**/package-lock.json') }}
          path: |
            ./node_modules
      - run: ls -la
      - run: echo Hello
      - run: npm run build
      - run: npm test

  sun-subflow:
    uses: kse-web-development-practice/react-examples/.github/workflows/reusable.yml@main
    with:
      some: 'some-parameter-here'
